import { Header } from '@/app/_components/Header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'タス | Blog',
  description: 'Generated by create next app',
};
const BlogLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <Header />
      <div className='bg h-14 bg-slate-100 bg-gradient-to-r from-cyan-500 to-blue-500 pt-24 md:px-7'>{children}</div>
    </>
  );
};
export default BlogLayout;
